# Generated by Django 4.0.3 on 2022-07-11 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_model',
            name='avatar',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
    ]
