# Generated by Django 4.0.3 on 2022-05-01 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_model',
            name='bg_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/user-profile'),
        ),
    ]
