# Generated by Django 4.0.3 on 2022-04-11 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_model',
            name='bg_image',
            field=models.ImageField(blank=True, default='images/curved0.jpg', null=True, upload_to='images/user-profile'),
        ),
    ]
