# Generated by Django 4.0.3 on 2022-04-11 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0002_user_model_bg_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_model',
            name='bg_image',
        ),
    ]
