# Generated by Django 4.0.3 on 2022-07-11 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0002_alter_user_model_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_model',
            name='avatar',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='images/user-profile'),
        ),
    ]
