# Generated by Django 4.0.3 on 2022-07-04 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0004_remove_work_samples_image_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_work_samples',
            name='image',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='account_module.work_samples_image'),
        ),
    ]
