# Generated by Django 4.0.3 on 2022-04-11 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0004_user_model_bg_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_model',
            name='theme_color',
            field=models.CharField(blank=True, default='blue', max_length=200, null=True),
        ),
    ]
