# Generated by Django 4.0.3 on 2022-04-09 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_image', models.ImageField(upload_to='', verbose_name='عکس اسلاید')),
                ('template_name', models.CharField(max_length=200, verbose_name='اسم اسلاید')),
                ('slug', models.SlugField(blank=True, default='', unique=True)),
            ],
            options={
                'verbose_name': 'عکس اسلایدر',
                'verbose_name_plural': 'عکس های اسلایدر',
            },
        ),
    ]
