# Generated by Django 4.0.3 on 2022-07-11 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='about_us_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='images/about-us')),
                ('text', models.TextField()),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='home_page_settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=200)),
                ('show_counter', models.BooleanField(verbose_name='نمایش تعداد رزومه ها')),
                ('home_page_image', models.ImageField(upload_to='images/home-page')),
                ('is_active', models.BooleanField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_image', models.ImageField(upload_to='images/slider-images', verbose_name='عکس اسلاید')),
                ('template_name', models.CharField(max_length=200, verbose_name='اسم اسلاید')),
                ('slug', models.SlugField(blank=True, default='', editable=False, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'عکس اسلایدر',
                'verbose_name_plural': 'عکس های اسلایدر',
            },
        ),
    ]
