# Generated by Django 4.0.3 on 2022-04-09 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home_page', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='template_image',
            field=models.ImageField(upload_to='images/slider-images', verbose_name='عکس اسلاید'),
        ),
    ]
