# Generated by Django 4.0.3 on 2022-04-09 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home_page', '0002_alter_slider_template_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='home_page_settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_counter', models.BooleanField(verbose_name='نمایش تعداد رزومه ها')),
                ('home_page_image', models.ImageField(upload_to='images/home-page')),
            ],
        ),
        migrations.AddField(
            model_name='slider',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='slider',
            name='slug',
            field=models.SlugField(blank=True, default='', editable=False, unique=True),
        ),
    ]
