# Generated by Django 4.0.3 on 2022-04-09 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home_page', '0004_home_page_settings_is_active_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='about_us',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('about_us_image', models.ImageField(upload_to='images/about-us')),
                ('text', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='home_page_settings',
            name='tittle',
        ),
        migrations.AddField(
            model_name='home_page_settings',
            name='title',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='home_page_settings',
            name='is_active',
            field=models.BooleanField(default=''),
        ),
    ]
