# Generated by Django 4.0.3 on 2022-04-09 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home_page', '0005_about_us_remove_home_page_settings_tittle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='about_us',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
