# Generated by Django 4.0.3 on 2022-04-09 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home_page', '0006_about_us_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about_us',
            old_name='about_us_image',
            new_name='image',
        ),
    ]
