# Generated by Django 4.0.3 on 2022-04-09 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home_page', '0007_rename_about_us_image_about_us_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='about_us',
            new_name='bout_us_model',
        ),
    ]
