# Generated by Django 4.0.3 on 2022-04-09 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home_page', '0008_rename_about_us_bout_us_model'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='bout_us_model',
            new_name='about_us_model',
        ),
    ]
