# Generated by Django 4.0.3 on 2022-07-11 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_module', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_model',
            name='category',
            field=models.ManyToManyField(to='blog_module.blog_category_model'),
        ),
    ]
