# Generated by Django 4.0.3 on 2022-07-16 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_module', '0004_blog_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog_tags',
            name='blog',
        ),
        migrations.AddField(
            model_name='blog_model',
            name='tags',
            field=models.ManyToManyField(blank=True, to='blog_module.blog_tags'),
        ),
    ]
