# Generated by Django 4.0.3 on 2022-04-17 17:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='user_socialmedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('social_media', models.CharField(max_length=200)),
                ('username', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='basic_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('job_title', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('military', models.CharField(choices=[('0', ''), ('1', 'مشمول'), ('2', 'در حال خدمت'), ('3', 'پایان خدمت'), ('4', 'معاف'), ('5', 'معافیت تحصیلی'), ('6', 'معافیت پزشکی'), ('7', 'معافیت غیر پزشکی')], default='0', max_length=50)),
                ('married', models.CharField(choices=[('0', ''), ('1', 'مجرد'), ('2', 'متاهل')], default='0', max_length=50)),
                ('sex', models.CharField(choices=[('0', ''), ('1', 'مرد'), ('2', 'زن')], default='0', max_length=50)),
                ('birth_day', models.CharField(default='', max_length=200, null=True)),
                ('birth_month', models.CharField(default='', max_length=200, null=True)),
                ('birth_year', models.CharField(default='', max_length=200, null=True)),
                ('phone', models.CharField(default='', max_length=200, null=True)),
                ('email', models.CharField(default='', max_length=200, null=True)),
                ('website', models.CharField(default='', max_length=200, null=True)),
                ('summary', models.TextField(default='', null=True)),
                ('user_base_info', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
