# Generated by Django 4.0.3 on 2022-08-02 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_resume_data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='resume_list_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('resume_id', models.CharField(blank=True, max_length=200, null=True)),
                ('template', models.FileField(blank=True, null=True, upload_to='resume_template/')),
            ],
            options={
                'verbose_name': 'Resume Template',
                'verbose_name_plural': 'Resume Template List',
            },
        ),
    ]
