# Generated by Django 4.0.3 on 2022-04-17 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_resume_data', '0002_alter_basic_info_user_base_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='basic_info',
            name='avatar',
            field=models.ImageField(default='', upload_to='images/user-profile'),
        ),
        migrations.AddField(
            model_name='basic_info',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='basic_info',
            name='resume_id',
            field=models.CharField(default='', max_length=200, null=True),
        ),
    ]
