# Generated by Django 4.0.3 on 2022-04-29 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_resume_data', '0002_alter_basic_info_city_alter_basic_info_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_education_model',
            name='text',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
