# Generated by Django 4.0.3 on 2022-04-17 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_resume_data', '0003_basic_info_avatar_basic_info_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basic_info',
            name='resume_id',
            field=models.CharField(default='', max_length=200, null=True, unique=True),
        ),
    ]
