# Generated by Django 4.0.3 on 2022-05-07 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_resume_data', '0005_user_projects_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_projects_model',
            name='project_user_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
