# Generated by Django 4.0.3 on 2022-04-18 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_resume_data', '0006_alter_basic_info_birth_month'),
    ]

    operations = [
        migrations.AddField(
            model_name='basic_info',
            name='social_media',
            field=models.ForeignKey(blank=True, default='', editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_resume_data.user_socialmedia'),
        ),
        migrations.AddField(
            model_name='user_socialmedia',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
