# Generated by Django 4.0.3 on 2022-04-18 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_resume_data', '0007_basic_info_social_media_user_socialmedia_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basic_info',
            name='resume_id',
            field=models.CharField(default='', max_length=200, null=True),
        ),
    ]
