# Generated by Django 4.0.3 on 2022-05-08 21:36

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_resume_data', '0009_user_entartaiment_model'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='user_entartaiment_model',
            new_name='user_entertainment_model',
        ),
        migrations.RenameField(
            model_name='user_entertainment_model',
            old_name='entartaiment_id',
            new_name='entertainment_id',
        ),
    ]
