# Generated by Django 4.0.3 on 2022-04-23 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_resume_data', '0009_user_socialmedia_social_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_langurage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('langurage', models.CharField(max_length=200)),
                ('grade', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='basic_info',
            name='langurage',
            field=models.ForeignKey(blank=True, default='', editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_resume_data.user_langurage'),
        ),
    ]
