# Generated by Django 4.0.3 on 2022-04-23 20:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_resume_data', '0010_user_langurage_basic_info_langurage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basic_info',
            name='langurage',
        ),
        migrations.AddField(
            model_name='user_langurage',
            name='user_base_info',
            field=models.ForeignKey(blank=True, default='', editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
