# Generated by Django 4.0.3 on 2022-05-11 20:28

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_resume_data', '0010_rename_user_entartaiment_model_user_entertainment_model_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='basic_info',
            new_name='basic_info_model',
        ),
        migrations.RenameModel(
            old_name='user_langurage',
            new_name='user_langurage_model',
        ),
        migrations.RenameModel(
            old_name='user_skill',
            new_name='user_skill_model',
        ),
        migrations.RenameModel(
            old_name='user_socialmedia',
            new_name='user_socialmedia_model',
        ),
    ]
