# Generated by Django 4.0.3 on 2022-04-23 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_resume_data', '0012_user_langurage_lang_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_langurage',
            name='user_base_info',
        ),
        migrations.AddField(
            model_name='basic_info',
            name='langurage',
            field=models.ForeignKey(blank=True, default='', editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_resume_data.user_langurage'),
        ),
    ]
