# Generated by Django 4.0.3 on 2022-04-24 19:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_resume_data', '0014_remove_basic_info_langurage_user_langurage_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(max_length=200)),
                ('grade', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('skill_id', models.CharField(default='', max_length=200, null=True)),
                ('user', models.ForeignKey(blank=True, default='', editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
